Query 2: Funcionarios por regiao e localizaçao
SELECT
    e.EMPLOYEE_ID,
    e.FIRST_NAME,
    e.LAST_NAME,
    e.SALARY,
    e.DEPARTMENT_ID,
    d.DEPARTMENT_NAME,
    l.LOCATION_ID,
    l.CITY,
    l.STATE_PROVINCE,
    c.COUNTRY_ID,
    c.COUNTRY_NAME,
    r.REGION_ID,
    r.REGION_NAME
FROM HR.EMPLOYEES e
LEFT JOIN HR.DEPARTMENTS d
    ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
LEFT JOIN HR.LOCATIONS l
    ON d.LOCATION_ID = l.LOCATION_ID
LEFT JOIN HR.COUNTRIES c
    ON l.COUNTRY_ID = c.COUNTRY_ID
LEFT JOIN HR.REGIONS r
    ON c.REGION_ID = r.REGION_ID
WHERE r.REGION_NAME IS NOT NULL
ORDER BY r.REGION_NAME, e.SALARY DESC;
